export const products = [
  { id: 1, name: "Rasasi Hawas Fire", brand: "Rasasi", price: 16990, category: "men", image: "/assets/products/hawas-fire.png", rating: 5, reviews: 124, description: "A bold, spicy oriental fragrance. Opens with peppery top notes and settles into a warm woody base. Hawas Fire is the signature scent for men who make an entrance — 24+ hours of longevity.", profileNotes: { top: "Black pepper, bergamot, cardamom", heart: "Cinnamon, amber, oud", base: "Sandalwood, musk, vanilla" }, longevity: "24+ hrs", projection: "High", bottleSize: "100ml", stock: 45 },
  { id: 2, name: "Armaf Lionheart Man", brand: "Armaf", price: 16500, category: "men", image: "/assets/products/lionheart.png", rating: 5, reviews: 89, description: "Aromatic and leathery masterpiece. Fresh citrus with deep leather accords — a sophisticated signature for professionals and adventurers.", profileNotes: { top: "Grapefruit, lemon, bergamot", heart: "Leather, cedarwood, geranium", base: "Oud, musk, vetiver" }, longevity: "20+ hrs", projection: "High", bottleSize: "100ml", stock: 32 },
  { id: 3, name: "Lattafa Khamrah Qahwa", brand: "Lattafa", price: 11000, category: "unisex", image: "/assets/products/khamrah-qahwa.webp", rating: 4.5, reviews: 156, description: "Sweet gourmand delight — arabica coffee, vanilla, dark chocolate. Khamrah Qahwa is like a warm embrace, perfect for cozy evenings.", profileNotes: { top: "Coffee beans, nutmeg", heart: "Vanilla, tonka bean, amber", base: "Musk, chocolate, woods" }, longevity: "18+ hrs", projection: "Moderate", bottleSize: "100ml", stock: 67 },
  { id: 4, name: "Lattafa Asad", brand: "Lattafa", price: 7490, category: "men", image: "/assets/products/asad.png", rating: 4.5, reviews: 203, description: "Lattafa's powerhouse — saffron, ambroxan, leather. Asad means 'lion' in Arabic, and this fragrance roars with confidence.", profileNotes: { top: "Saffron, pepper", heart: "Leather, oud", base: "Ambroxan, musk" }, longevity: "16+ hrs", projection: "High", bottleSize: "100ml", stock: 89 },
  { id: 5, name: "Afnan 9pm REBEL", brand: "Afnan", price: 13990, category: "men", image: "/assets/products/9pm-rebel.png", rating: 5, reviews: 112, description: "Smoky tobacco with vanilla — after-dark only. Dark, mysterious, and wearable. A standout for evening events.", profileNotes: { top: "Cinnamon, ginger", heart: "Tobacco leaf, vanilla", base: "Amber, musk, woods" }, longevity: "20+ hrs", projection: "High", bottleSize: "100ml", stock: 54 },
  { id: 6, name: "Lattafa Hayaati", brand: "Lattafa", price: 7890, category: "women", image: "/assets/products/hayaati.webp", rating: 4.5, reviews: 178, description: "Apple, cinnamon, vanilla — cozy after-hours warmth. Hayaati is perfect for intimate moments and relaxed evenings.", profileNotes: { top: "Red apple, cinnamon", heart: "Vanilla, caramel", base: "Musk, wood" }, longevity: "14+ hrs", projection: "Moderate", bottleSize: "100ml", stock: 78 },
  { id: 7, name: "Rasasi Hawas Elixir", brand: "Rasasi", price: 17500, category: "men", image: "/assets/products/hawas-elixir.webp", rating: 5, reviews: 98, description: "Honeyed tobacco — Rasasi's gold edition. Combines sweetness with smoky depth. For those who appreciate refined complexity.", profileNotes: { top: "Tobacco, honey", heart: "Amber, oud", base: "Sandalwood, vanilla" }, longevity: "24+ hrs", projection: "High", bottleSize: "100ml", stock: 28 },
  { id: 8, name: "Armaf Maleka", brand: "Armaf", price: 9990, category: "women", image: "/assets/products/maleka.png", rating: 4.5, reviews: 134, description: "Oriental floral with jasmine and rose. Armaf Maleka means 'queen' — regal elegance for special occasions.", profileNotes: { top: "Bergamot, pink pepper", heart: "Jasmine, rose, peach", base: "Oud, amber, musk" }, longevity: "18+ hrs", projection: "Moderate", bottleSize: "100ml", stock: 61 },
];

export const getProductById = (id) => products.find((p) => p.id === parseInt(id));
export const getProductsByCategory = (cat) => cat === "all" ? products : products.filter((p) => p.category === cat);
